# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProductCatalogue.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16ProductCatalogue.proto\x12\x07product\"#\n\x15ProductDetailsRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"[\n\x13ProductDetailsReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03sku\x18\x03 \x01(\t\x12\x1d\n\x05price\x18\x04 \x01(\x0b\x32\x0e.product.Price\"-\n\x05Price\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x02\x12\x14\n\x0c\x63urrencyCode\x18\x02 \x01(\t2c\n\x0eProductCatalog\x12Q\n\x11GetProductDetails\x12\x1e.product.ProductDetailsRequest\x1a\x1c.product.ProductDetailsReplyb\x06proto3')



_PRODUCTDETAILSREQUEST = DESCRIPTOR.message_types_by_name['ProductDetailsRequest']
_PRODUCTDETAILSREPLY = DESCRIPTOR.message_types_by_name['ProductDetailsReply']
_PRICE = DESCRIPTOR.message_types_by_name['Price']
ProductDetailsRequest = _reflection.GeneratedProtocolMessageType('ProductDetailsRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTDETAILSREQUEST,
  '__module__' : 'ProductCatalogue_pb2'
  # @@protoc_insertion_point(class_scope:product.ProductDetailsRequest)
  })
_sym_db.RegisterMessage(ProductDetailsRequest)

ProductDetailsReply = _reflection.GeneratedProtocolMessageType('ProductDetailsReply', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTDETAILSREPLY,
  '__module__' : 'ProductCatalogue_pb2'
  # @@protoc_insertion_point(class_scope:product.ProductDetailsReply)
  })
_sym_db.RegisterMessage(ProductDetailsReply)

Price = _reflection.GeneratedProtocolMessageType('Price', (_message.Message,), {
  'DESCRIPTOR' : _PRICE,
  '__module__' : 'ProductCatalogue_pb2'
  # @@protoc_insertion_point(class_scope:product.Price)
  })
_sym_db.RegisterMessage(Price)

_PRODUCTCATALOG = DESCRIPTOR.services_by_name['ProductCatalog']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCTDETAILSREQUEST._serialized_start=35
  _PRODUCTDETAILSREQUEST._serialized_end=70
  _PRODUCTDETAILSREPLY._serialized_start=72
  _PRODUCTDETAILSREPLY._serialized_end=163
  _PRICE._serialized_start=165
  _PRICE._serialized_end=210
  _PRODUCTCATALOG._serialized_start=212
  _PRODUCTCATALOG._serialized_end=311
# @@protoc_insertion_point(module_scope)
